### ISSUE TITLE
Documentation link gives 404

### ISSUE THREAD

**Issue by syberphunk** [microstack-IoT/python3-microstackcommon#1]
http://microstack-iot.github.io/ does not go to a valid page.

**Comment by tompreston** [comment]
We're aware of this one. We're hoping to get the docs up on https://readthedocs.org/. For now there are PDF's available on the Farnell website.

**Comment by syberphunk** [comment]
Looks like you've got one for https://github.com/microstack-IoT/python3-microstacknode but not https://github.com/microstack-IoT/python3-microstackcommon yet.

**Comment by tompreston** [comment]
We don't have docs for Microstack Common at the moment since it's not intended to be used on its own. It's really just a dependency for other Microstack things. I'll remove the links in the Readme, thanks.
